export const LIST_ALL_CUSTOMERS_SUCCESS =  'LIST_ALL_CUSTOMERS_SUCCESS';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';

